content/geometry/general-structure-index.adoc

To fix the incorrect file structure in the antora publishing pipeline

Fix html for geometry chapter

---

content/geometry/File_format_support.adoc

Add a bit more description to the supported file formats. The list of file formats was already on the main branch.
Fixes #61

Add more description to the file format chapter

---

.antora/modules/specification/nav_openmaterial.adoc

Fix navbar
#75 
@LudwigFriedmann

Fix navbar

---

content/geometry/object-human/human-model-structure.adoc

Synchronize miro-board, structure and sub-chapters, e.g. articulated hands, helper bones, transforms
#79 
Add @ClemensLinnhoff

Add fixes, complete structure

---

examples/example_asset.xoma
schemas/asset_schema.json

Add the following meta data:
Fixes #62

Add asset meta data

---

.antora/modules/specification/nav_openmaterial.adoc
antora-playbook.yml

Fix navbar and add local search path to antora playbook
#52

52 automatically create schema documentation from json schema files

---

content/geometry/object-human/human-model-structure.adoc
content/geometry/object-road-network/road-model-structure.adoc
content/geometry/object-vehicle/vehicle-structure-model-structure.adoc

Update hierarchy levels

---

.github/workflows/antora-build.yml
.gitmodules
antora-playbook.yml
content/geometry/geometry-index.adoc
content/index.adoc
content/material/material-index.adoc
content/nav-openmaterial.adoc
run-build.sh

Added the submodule 'asam-antora-extensions' from [here](https://code.asam.net/common/asam-antora-extensions). This submodule enables enhanced functionality, i.e. for numbered headings and graphical representation of structure models.
This pull request should fix the issues #66 and #77.
Please note, that in order to ensure the correct generation of numbered headings, the navigation-file '.antora\modules\specification\nav-openmaterial.adoc' is deprecated and the file 'content\nav-openmaterial.adoc' should be used instead. (The old file has to be kept though, as the asam-antora-extensions rely on this file and overwrite it in the generation process).
Also, in the files 'geometry/geometry-index.adoc' and 'material/material-index.adoc', the include:: macros have been replaced by xref: macros. …

Add asam antora extensions

---

.github/workflows/antora-build.yml

Fix naming convention in build workflow
Fixes #115

Fix naming convention in pipeline

---

.github/workflows/antora-build.yml

I forgot to change the filename, too.
#115
Sorry @AsamDiegoSanchez could you review again?

Change mv command

---

examples/example_material.xomp
examples/example_material_emp.xompt
schemas/material_emp_schema.json
schemas/material_schema.json

Add source field to roughness and electromagnetic properties
#95

#95 add source field to all remaining properties

---

.antora/modules/specification/nav-openmaterial.adoc

Improved structure of navigation files, removed obsolete content, added explaining comments in resprective file
relates to issue #139

improve structure of navigation files

---

content/geometry/object-vehicle/vehicle-structure.adoc

Fix rearview mirror name in structure
Fixes #151

Fix rearview mirror name in structure

---

content/general-docs/introduction.adoc
content/geometry/introduction.adoc

161 workover chapter 71 introduction

---

content/geometry/file-format-support.adoc

Add links to 3D model file format specifications and state special considerations.
Fixes #135

Elaborate on file format support

---

.antora/antora.yml
antora-playbook.yml
content/nav-openmaterial.adoc

- enabled generation of bibliography
- fixed link to .bib file in antora.yml
- fixed entry for bibliography in navigation file
- solves issue #174

Fix bibliography

---

content/geometry/object-vehicle/vehicle-structure.adoc

Fix blindspot joint headline, remove wrong side mirrors from doors

---

content/geometry/object-classes.adoc

Review Chapter 7.1 Introduction
- Rename "road network" to environment
- Add links from the bullet points to the class-specific sections
- Remove chapter 7.3.2
#163 
@ClemensLinnhoff and @FKlopfer can you briefly review and merge?

Review Chapter 7.3 Object Classes

---

content/geometry/object-classes.adoc
content/geometry/object-vehicle/vehicle-general.adoc
content/geometry/object-vehicle/vehicle-structure.adoc

Fix links in object classes chapter
Fixes https://github.com/asam-ev/OpenMATERIAL/issues/190 and align content with https://github.com/asam-ev/OpenMATERIAL/pull/194

190-links-in-object-classes-do-not-work-properly

---

content/geometry/object-vehicle/vehicle-structure.adoc

Adapt changes as requested in https://github.com/asam-ev/OpenMATERIAL/issues/191
- Adapt figure size (make them smaller)
- Add captions to all figures
- Add table titles and table headings
- I am not sure where the new sentence for doors (that they can be opened via a positive rotation around the z-axis) should be added. This information is already included in the description of the z-axes in the tables. Should they be added (that is, repeated) in the description of the doors?
https://github.com/asam-ev/OpenMATERIAL/issues/191

Improvements of vehicle structure chapter

---

schemas/asset_schema.json

- Added some more detailed description on every element of the metadata in the asset schema
- few units and data types were clearly written
- a url to the asset file chapter (7.2.4) was added. 
Add a reference to a related issue.
Add @mentions of the person or team responsible for reviewing the proposed changes.

Review Metadata section in asset schema #136

---

content/geometry/object-classes.adoc
content/geometry/object-environment/environment-index.adoc
content/geometry/object-vehicle/vehicle-index.adoc
content/geometry/object-vehicle/vehicle-structure-notes.adoc

- Fix headline of environment section
- Remove notes from vehicle chapter
Closes #202, closes #150

202 fix environment headline, 150 remove vehicle notes

---

schemas/asset_schema.json
schemas/material_schema.json

Fix schemas that have been broken due to a merge conflict

Fix asset schema

---

content/geometry/geometry-index.adoc
content/geometry/performance.adoc
content/nav-openmaterial.adoc

Remove performance section
Closes #137

Remove performance section

---

.antora/antora.yml
content/geometry/object-vehicle/vehicle-structure.adoc
content/nav-openmaterial.adoc

- Add comment anchors to tables and figures in vehicle chapter so they show up in the list of tables and list of figures
- Add missing (empty) nav_loft.adoc file that is needed for the antora pipeline

Create list of figures and list of tables

---

content/geometry/general.adoc

Add discussed changes to the world and local coordinates.
The remaining points in the linked issues already have separate issues, so we can close #162 with this PR.
Closes #162

162 workover chapter 72 general

---

content/geometry/introduction.adoc

Add concept of relative paths to model reference definition
#192

Enhance model reference description

---

examples/example_asset.xoma
examples/example_mapping.xomm
examples/example_material.xomp
examples/example_material_2.xomp
examples/example_material_camera_brdf.xompt
examples/example_material_emp.xompt
examples/example_material_lidar_brdf.xompt
examples/example_material_optical.xompt
examples/example_material_radar_brdf.xompt
schemas/asset_schema.json
schemas/mapping_schema.json
schemas/material_brdf_schema.json
schemas/material_emp_schema.json
schemas/material_optical_schema.json
schemas/material_schema.json

- Change UUID format in schemas and exmaple files
- I also fixed the file formatting. That's why there appear to be more changes. But that's just spacing.
Fixes #221

Put UUIDs in 8-4-4-4-12 format

---

content/geometry/object-environment/environment-general.adoc
content/geometry/object-vehicle/vehicle-general.adoc
content/geometry/object-vehicle/vehicle-structure.adoc

Add (T) indicators to vehicle structure and environment general section
Fixes #214

Add (T) indicators to vehicle structure and environment general section

---

content/use-cases/use-cases.adoc

The correct company name is "IPG Automotive".

Correct IPG Automotive company name

---

examples/example_mapping.xomm
schemas/asset_schema.json
schemas/mapping_schema.json
schemas/material_brdf_schema.json
schemas/material_emp_schema.json
schemas/material_optical_schema.json
schemas/material_schema.json
scripts/json2asciidoc.py

- Change required fields
- Harmonize field descriptions
Fixes #143

143 required fields in the material schema

---

content/geometry/file-format-support.adoc

Add glb support to gltf section
Fixes #231

Add glb support to gltf section

---

content/geometry/general.adoc
content/geometry/introduction.adoc

Remove obsolete note and rename headline from Use-Cases to Applications. 
-
-
Add a reference to a related issue.
-
@ClemensLinnhoff can you have a  brief look?

Cleanup Geometry Chapter

---

content/material/introduction.adoc

Add introduction for material chapter
Fixes #223

Add introduction for material chapter

---

content/index.adoc
content/nav-openmaterial.adoc

Add reflectance to nav bar
Fixes #240

Add reflectance to nav bar

---

content/geometry/object-vehicle/vehicle-structure.adoc
examples/vehicle_example/vehicle_example.gltf

- Add grp root to vehicle structure
Fixes #232

Add grp root to vehicle structure

---

content/general-docs/introduction.adoc

Add deliverables to introduction
The links to human and environment do not work yet, but they will, when the examples are added.
Fixes #229

Add deliverables

---

scripts/json2asciidoc.py

Add enums to documentation
Fixes #246

Add enums to documentation

---

content/general-docs/introduction.adoc

Further information added in the introduction about how the standard is structured and how the users can be conform with.
https://github.com/asam-ev/OpenMATERIAL/issues/169

Introduction update to add clarity about the Material/Geometry compliance of the standard

---

content/index.adoc
content/nav-openmaterial.adoc

Remove (empty) annex from nav file.
[Add a reference to a related issue.](https://github.com/asam-ev/OpenMATERIAL/issues/256)

Remove annex

---

content/nav-openmaterial.adoc

Fix material chapter in nav bar

Fix material chapter in nav bar

---

content/geometry/object-environment/environment-structure.adoc
content/geometry/object-vehicle/vehicle-structure.adoc

Remove (T) from Grp_Root nodes
Fixes #266

Remove (T) from Grp_Root nodes

---

content/general-docs/introduction.adoc

Remove numbers from subsections in introduction.
Fixes #230

Introduction sections should not have numbers

---

.antora/antora.yml
antora-playbook.yml
content/_config.adoc
content/general-docs/introduction.adoc
content/geometry/file-format-support.adoc
content/geometry/general.adoc
content/geometry/introduction.adoc
content/geometry/object-classes.adoc
content/geometry/object-environment/environment-structure.adoc
content/index.adoc
content/material/introduction.adoc
content/terms-and-definitions/terms-and-definitions.adoc
examples/README.md
examples/example_asset.xoma
examples/example_material_2.xomp
examples/human_example/human_example.xoma
examples/vehicle_example/vehicle_example.xoma
schemas/asset_schema.json
schemas/mapping_schema.json
schemas/material_brdf_schema.json
schemas/material_emp_schema.json
schemas/material_optical_schema.json
schemas/material_reflectance_schema.json
schemas/material_schema.json

- Change the name to  "ASAM OpenMATERIAL 3D"
- Replace the written  "ASAM OpenMATERIAL 3D" with the placeholder {THIS_STANDARD}
- Change the value of the placeholder to   "ASAM OpenMATERIAL 3D"
[Add a reference to a related issue.](https://github.com/asam-ev/OpenMATERIAL/issues/262)

Change name to "ASAM OpenMATERIAL 3D"

---

content/general-docs/introduction.adoc

- Add "Use Cases" chapter to table about informative and normative content
- Change order of the table to reflect table of content
Fixes #269

Add "Use Cases" chapter to table about informative and normative content

---

content/geometry/general.adoc

Changed chapter "Dimensions" as described in https://github.com/asam-ev/OpenMATERIAL/issues/286.

Improve units/dimensons chapter

---

content/general-docs/foreword.adoc

Foreword was updated with standard-specific information
(see Editorial Guide: https://internal.pages.asam.net/asam-editorial-guide/editorial-guide-generator/editorialguide-asciidoc/1.0.0/Editorial_guide/02_structure.html)
fixes #281

Update foreword with standard specific information

---

.github/workflows/antora-build-local.yml

added value to workflow file to trigger on every push on a pull request.
Solves issue #278

modify workflow to trigger on every push on pull request

---

schemas/asset_schema.json

Add more details to the mesh count description due to potentially changing number of meshes during export of the model.
Fixes #293

More detailed mesh count description

---

content/geometry/object-environment/environment-structure.adoc
content/geometry/object-vehicle/vehicle-structure.adoc
content/nav-openmaterial.adoc

- Update nav-openmaterial file so that the table and figures are numbered in correct order
- Add missing anchors for some tables and figures
[Add a reference to a related issue.](https://github.com/asam-ev/OpenMATERIAL/issues/290)

Correct table and figure numbering

---

content/geometry/object-human/human-general.adoc

Make human structure figure caption prettier
Add a reference to a related issue.Fixes #299

Fix human structure figure caption

---

content/geometry/object-human/human-structure.adoc

Add anchors to tables in human chapter so they show up in the LoT.

Add anchors to tables in human chapter

---

content/geometry/object-classes.adoc
content/geometry/object-other/other-general.adoc

Minor clarifications on the other object class documentation.
-
-
@ClemensLinnhoff can you have a brief look?

Minor clarification on other object class documentation

---

content/geometry/object-environment/environment-structure.adoc

Add clarifications on group character and coordinate systems of environment structure nodes.
- Clarifications added
#313 
@ClemensLinnhoff, @ipg-sig, @KimuraDIVP, @MatthiasThDs, @AsamDiegoSanchez, @lyndyRott

Add clarifications to environment section

---

content/geometry/object-environment/environment-structure.adoc

Add link to OpenDRIVE inertial coordinate system
Fixes #324

Add link to OpenDRIVE

---

README.md

Update name of the standard in readme file (ASAM OpenMATERIAL --> ASAM OpenMATERIAL 3D)
https://github.com/asam-ev/OpenMATERIAL/issues/311

311-Update name of the standard in readme file

---

.github/workflows/antora-build.yml
antora-playbook.yml
content/general-docs/introduction.adoc
content/geometry/object-environment/environment-general.adoc

- Repair broken links by adding "-3D" to urls in the files
- Also adding "-3D" to the github urls (although Github is able to redirect the links) 
[Add a reference to a related issue.](https://github.com/asam-ev/OpenMATERIAL-3D/issues/330)

Repair broken links after repo name changed

---

antora-playbook.yml
content/general-docs/introduction.adoc
content/index.adoc

- Correct position of trademark
- Adapt disclaimer
As the two issues are very small, I created one PR for both.
https://github.com/asam-ev/OpenMATERIAL-3D/issues/332, https://github.com/asam-ev/OpenMATERIAL-3D/issues/333

Correct position of trademark, correct disclaimer

---

antora-playbook.yml

Remove extra 'ASAM' from headline
[Add a reference to a related issue.](https://github.com/asam-ev/OpenMATERIAL-3D/issues/338)

Remove extra 'ASAM' from headline

---

content/use-cases/use-cases.adoc

Change "parts" to "chapters" in tables in use case chapter
[Add a reference to a related issue.](https://github.com/asam-ev/OpenMATERIAL-3D/issues/345)

Update wording in use case chapter

---

content/general-docs/abbreviations.adoc
content/general-docs/introduction.adoc
content/index.adoc
content/terms-and-definitions/terms-and-definitions.adoc

I've checked for the glossary terms and have added some accordingly. This PR fixes #128 :)

Update Glossary and Terms and Definitions

---

content/geometry/object-human/human-structure.adoc

Fix origin of root bone
Fixes #352

Fix origin of root bone

---

content/geometry/object-environment/environment-structure.adoc
content/geometry/object-human/human-structure.adoc
content/geometry/object-vehicle/vehicle-structure.adoc

- Repair broken links in vehicle, human, and environment chapter
- Adapt node overview in human chapter
- Checked all links in the structures of all object classes.
[Add a reference to a related issue.](https://github.com/asam-ev/OpenMATERIAL-3D/issues/363)

Repair broken links

---

content/general-docs/normative-references.adoc
content/geometry/general.adoc
content/geometry/introduction.adoc
content/terms-and-definitions/terms-and-definitions.adoc
examples/scenario_example/README.md
schemas/asset_schema.json

Better distinguish between OpenSCENARIO XML and DSL
Fixse #366

Specify OpenSCENARIO XML more accurately

---

content/general-docs/abbreviations.adoc
content/general-docs/introduction.adoc
content/general-docs/scope.adoc
content/geometry/general.adoc
content/geometry/introduction.adoc
content/geometry/object-classes-introduction.adoc
content/geometry/object-environment/environment-structure.adoc
content/geometry/object-human/human-structure.adoc
content/geometry/object-other/other-general.adoc
content/geometry/object-vehicle/vehicle-naming-convention.adoc
content/geometry/object-vehicle/vehicle-structure.adoc
content/material/introduction.adoc
content/use-cases/use-cases.adoc
examples/environment_example/environment_example.xoma
examples/example_asset.xoma
examples/example_material_lidar_brdf.xompt
examples/human_example/human_example.xoma
examples/vehicle_example/vehicle_example.xoma
schemas/asset_schema.json
schemas/material_brdf_schema.json
schemas/material_emp_schema.json
schemas/material_optical_schema.json
schemas/material_reflectance_schema.json

We had another internal language review. Most of the changes are quite small:
- Correct grammer and spelling mistakes 
- Improve readability of sections, e.g. by creating lists out of paragraphs
- Adapt formulations
- Also fixes remark 1 from https://github.com/asam-ev/OpenMATERIAL-3D/issues/373

Additional language review

---

schemas/material_brdf_schema.json
schemas/material_emp_schema.json
schemas/material_optical_schema.json
schemas/material_reflectance_schema.json

- Add free-space to wavelength definition
- Specify relative humidity

Add free-space to wavelength definition

---

content/05_terms_and_definitions/terms-and-definitions.adoc

Add distinction to JSON object data type to terms and definition
Fixes #367

Add distinction to JSON object data type to terms and definition

---

content/01_scope/scope.adoc

Add geometry and material to scope
Fixes #385

Add geometry and material to scope

---

content/07_geometry/object-classes-introduction.adoc

Add explanation sentence about environment.
Fixes #387

Add explanation sentence about environment.

---

antora-playbook.yml
supplemental_ui/partials/header-content.hbs

- Changed title in the Header from "OpenMATERIAL 3D" to "ASAM OpenMATERIAL 3D"
- Move title to the right 
- Use "supplemental_ui" (https://docs.antora.org/antora/latest/playbook/ui-supplemental-files/)

Move title to the right in the header

---

content/00_preface/introduction.adoc
content/07_geometry/introduction.adoc

* Move the information on interaction of OpenMATERIAL 3D with other ASAM standards from the geometry chapter to the general introduction
* Add brief explanation on the role of 3D models as connecting link between the standards
- Interaction with other standards is moved to a more prominent position
- A brief explanation about the special role of 3D models is given
#390 
@ClemensLinnhoff @AsamDiegoSanchez

Interaction with other standards

---

content/index.adoc

remove "public release candidate" from title and prepare the final text
fixes https://github.com/asam-ev/OpenMATERIAL-3D/issues/407

remove "public release candidate" from title 

---

content/09_annexes/checker-rules.adoc
schemas/material_emp_schema.json
schemas/material_optical_schema.json

- Add "relative" to permittivity and permeability
- Add equations
The documentation now looks like this:
Edit: As suggested by @lyndyRott, I changed n'' to kappa:
Fixes #370, fixes #391

Add relative to permittivity and permeability

---

schemas/material_reflectance_schema.json

Add description sentence to plane of polarization.
Fixes #364

Add description sentence to plane of polarization.

---

examples/environment_example/environment_example.xoma
examples/example_asset.xoma
examples/example_mapping.xomm
examples/example_material.xomp
examples/example_material_2.xomp
examples/example_material_camera_brdf.xompt
examples/example_material_emp.xompt
examples/example_material_lidar_brdf.xompt
examples/example_material_optical.xompt
examples/example_material_radar_reflectance.xompt
examples/human_example/human_example.xoma
examples/vehicle_example/vehicle_example.xoma
schemas/asset_schema.json
schemas/mapping_schema.json
schemas/material_brdf_schema.json
schemas/material_emp_schema.json
schemas/material_optical_schema.json
schemas/material_reflectance_schema.json
schemas/material_schema.json

Change openMaterialVersion to openMaterial3dVersion
Fixes #404

Change openMaterialVersion to openMaterial3dVersion

---

.github/workflows/validate-json.yaml
content/00_preface/foreword.adoc
content/00_preface/introduction.adoc
content/08_material/introduction.adoc
content/08_material/material-index.adoc
content/index.adoc
content/nav-openmaterial.adoc
examples/example_material.xomp
examples/example_material_radar_reflCoeff.xompt
schemas/material_reflection_coefficient_schema.json
schemas/material_schema.json
scripts/generate_schema_docs.py

Change reflectance to reflection coefficient
Fixes #392

Change reflectance to reflection coefficient

---

schemas/asset_schema.json

Remove minimum value of axle x position
Fixes #420

Remove minimum value of axle x position

---

.antora/antora.yml
.github/workflows/antora-build.yml
.github/workflows/release.yml
antora-playbook.yml

Added github workflow to build and commit the asciidoc files automatically generated from schema files.
Included tags in the build workflow.
#317

317 release process and versioning

---

content/index.adoc

Test changing the version number

Add test version

---

antora-playbook.yml
supplemental_ui/partials/toolbar.hbs

Readded the supplemental UI files and created toolbar.hbs to remove the edit-this-page button.
#426

426 remove edit button in documentation

---

.antora/antora.yml

Adapted the naming scheme to allow the build of release tags (i.e. "v1.0.0-rc1")

add scheme to include rc tags

---

content/00_preface/foreword.adoc
content/00_preface/introduction.adoc
content/06_use_cases/use-cases.adoc
content/07_geometry/introduction.adoc
content/07_geometry/object-vehicle/vehicle-structure.adoc
content/08_material/introduction.adoc

Changing the word "chapter" by "segment" and "section"
fixes #442

442 change the word chapter by segment
